import { formatPrice } from './menu-utils.mjs';
const cfg=window.CHANTEA_CONFIG; const db=window.supabase.createClient(cfg.supabaseUrl,cfg.supabaseKey);
const $=s=>document.querySelector(s), authCard=$('#authCard'), manager=$('#manager'), logoutBtn=$('#logoutBtn'), list=$('#adminList');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function publicUrl(path){return path?db.storage.from(cfg.imageBucket).getPublicUrl(path).data.publicUrl:''}
function setAuth(on){authCard.classList.toggle('hidden',on);manager.classList.toggle('hidden',!on);logoutBtn.classList.toggle('hidden',!on);if(on)loadItems()}
async function refreshSession(){const {data:{session}}=await db.auth.getSession();setAuth(!!session)}
$('#loginBtn').onclick=async()=>{const email=$('#email').value.trim(),password=$('#password').value;$('#authMsg').textContent='Đang đăng nhập...';const {error}=await db.auth.signInWithPassword({email,password});if(error){$('#authMsg').textContent=error.message;return}$('#authMsg').textContent='';setAuth(true)};
$('#signupBtn').onclick=async()=>{const email=$('#email').value.trim(),password=$('#password').value;if(password.length<6){$('#authMsg').textContent='Mật khẩu cần ít nhất 6 ký tự.';return}const {data,error}=await db.auth.signUp({email,password});$('#authMsg').textContent=error?error.message:(data.session?'Tạo tài khoản thành công.':'Đã tạo tài khoản. Kiểm tra email xác nhận rồi đăng nhập.');if(data.session)setAuth(true)};
logoutBtn.onclick=async()=>{await db.auth.signOut();setAuth(false)};
async function loadItems(){const st=$('#adminStatus');st.textContent='Đang tải...';const {data,error}=await db.from('menu_items').select('*').order('category').order('sort_order').order('id');if(error){st.textContent='Không có quyền hoặc lỗi tải dữ liệu: '+error.message;return}st.textContent=data.length?`${data.length} món`:'Chưa có món nào.';list.innerHTML=data.map(i=>{const img=publicUrl(i.image_path);const price=i.price_single?formatPrice(i.price_single):`M ${formatPrice(i.price_m)||'—'} · L ${formatPrice(i.price_l)||'—'}`;return `<article class="admin-item"><div class="admin-thumb">${img?`<img src="${esc(img)}" alt="">`:'<span>Ảnh</span>'}</div><div class="admin-item-info"><small>${esc(i.category)}</small><strong>${esc(i.name)}</strong><span>${price} · ${i.available?'Còn hàng':'Hết hàng'}</span></div><div class="admin-actions"><button class="secondary edit" data-id="${i.id}">Sửa</button><button class="danger del" data-id="${i.id}">Xóa</button></div></article>`}).join('');list.querySelectorAll('.edit').forEach(b=>b.onclick=()=>editItem(data.find(i=>i.id==b.dataset.id)));list.querySelectorAll('.del').forEach(b=>b.onclick=()=>deleteItem(data.find(i=>i.id==b.dataset.id)))}
function openForm(){ $('#modal').classList.remove('hidden') } function closeForm(){ $('#modal').classList.add('hidden');$('#itemForm').reset();$('#available').checked=true;$('#sortOrder').value=0;$('#itemId').value='';$('#oldImagePath').value='';$('#preview').classList.add('hidden');$('#formMsg').textContent=''}
$('#addBtn').onclick=()=>{$('#formTitle').textContent='Thêm món';openForm()};$('#closeBtn').onclick=closeForm;$('#modal').onclick=e=>{if(e.target.id==='modal')closeForm()};
$('#image').onchange=e=>{const f=e.target.files[0];if(!f)return;const p=$('#preview');p.src=URL.createObjectURL(f);p.classList.remove('hidden')};
function editItem(i){$('#formTitle').textContent='Sửa món';$('#itemId').value=i.id;$('#oldImagePath').value=i.image_path||'';$('#category').value=i.category;$('#name').value=i.name;$('#priceSingle').value=i.price_single??'';$('#priceM').value=i.price_m??'';$('#priceL').value=i.price_l??'';$('#available').checked=i.available;$('#sortOrder').value=i.sort_order??0;const u=publicUrl(i.image_path);if(u){$('#preview').src=u;$('#preview').classList.remove('hidden')}openForm()}
function n(v){return v===''?null:Number(v)}
async function uploadImage(file){if(!file)return null;if(file.size>5*1024*1024)throw new Error('Ảnh vượt quá 5 MB.');const ext=(file.name.split('.').pop()||'jpg').toLowerCase();const path=`${Date.now()}-${crypto.randomUUID()}.${ext}`;const {error}=await db.storage.from(cfg.imageBucket).upload(path,file,{cacheControl:'3600',upsert:false});if(error)throw error;return path}
$('#itemForm').onsubmit=async e=>{e.preventDefault();const msg=$('#formMsg'),btn=$('#saveBtn');btn.disabled=true;msg.textContent='Đang lưu...';let newPath=null;try{const ps=n($('#priceSingle').value),pm=n($('#priceM').value),pl=n($('#priceL').value);if(ps===null&&pm===null&&pl===null)throw new Error('Phải nhập ít nhất một giá.');newPath=await uploadImage($('#image').files[0]);const old=$('#oldImagePath').value;const row={category:$('#category').value.trim(),name:$('#name').value.trim(),price_single:ps,price_m:pm,price_l:pl,available:$('#available').checked,sort_order:Number($('#sortOrder').value||0),image_path:newPath||old||null};const id=$('#itemId').value;const q=id?db.from('menu_items').update(row).eq('id',id):db.from('menu_items').insert(row);const {error}=await q;if(error)throw error;if(newPath&&old)await db.storage.from(cfg.imageBucket).remove([old]);closeForm();await loadItems()}catch(err){if(newPath)await db.storage.from(cfg.imageBucket).remove([newPath]);msg.textContent=err.message||'Không lưu được.'}finally{btn.disabled=false}};
async function deleteItem(i){if(!confirm(`Xóa món “${i.name}”?`))return;const {error}=await db.from('menu_items').delete().eq('id',i.id);if(error){alert('Không xóa được: '+error.message);return}if(i.image_path)await db.storage.from(cfg.imageBucket).remove([i.image_path]);loadItems()}
db.auth.onAuthStateChange((_e,s)=>setAuth(!!s));refreshSession();
