import { groupByCategory, getDisplayPrice } from './menu-utils.mjs';
const cfg=window.CHANTEA_CONFIG; const db=window.supabase.createClient(cfg.supabaseUrl,cfg.supabaseKey);
const menu=document.querySelector('#menu'), status=document.querySelector('#status'), nav=document.querySelector('#categoryNav');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const slug=s=>String(s??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/đ/g,'d').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')||'danh-muc';
function imageUrl(path){if(!path)return '';if(/^https?:\/\//i.test(path))return path;return db.storage.from(cfg.imageBucket).getPublicUrl(path).data.publicUrl}
function card(item){const p=getDisplayPrice(item);const prices=p.single?`<strong class="single-price">${p.single}</strong>`:`<span>M <strong>${p.m||'—'}</strong></span><span>L <strong>${p.l||'—'}</strong></span>`;const img=imageUrl(item.image_path);return `<article class="menu-card ${item.available?'':'sold-out'}"><div class="food-image">${img?`<img src="${esc(img)}" alt="${esc(item.name)}" loading="lazy" referrerpolicy="no-referrer">`:'<div class="no-image">CHAN TEA</div>'}</div><div class="food-info"><h3>${esc(item.name)}</h3>${item.available?`<div class="prices">${prices}</div>`:'<span class="sold-badge">HẾT HÀNG</span>'}</div></article>`}
function renderNav(groups){nav.innerHTML=groups.map((g,i)=>`<button class="category-tab ${i===0?'active':''}" data-target="cat-${slug(g.category)}">${esc(g.category)}</button>`).join('');nav.classList.remove('hidden');nav.querySelectorAll('.category-tab').forEach(btn=>btn.addEventListener('click',()=>{nav.querySelectorAll('.category-tab').forEach(x=>x.classList.remove('active'));btn.classList.add('active');document.getElementById(btn.dataset.target)?.scrollIntoView({behavior:'smooth',block:'start'})}))}
async function load(){status.textContent='Đang tải menu...';const {data,error}=await db.from('menu_items').select('*').order('sort_order').order('id');if(error){status.textContent='Không tải được menu. Vui lòng thử lại.';return}if(!data.length){status.textContent='Menu đang được cập nhật.';return}const groups=groupByCategory(data);status.classList.add('hidden');renderNav(groups);menu.innerHTML=groups.map(g=>`<section class="category" id="cat-${slug(g.category)}"><h2>${esc(g.category)}</h2><div class="category-items">${g.items.map(card).join('')}</div></section>`).join('')}
load();
